question_data = [{"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The Spitfire originated from a racing plane.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "In &quot;Mario Kart 64&quot;, Waluigi is a playable character.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                  "question": "American rapper Dr. Dre actually has a Ph.D. doctorate.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "The 2010 film &quot;The Social Network&quot; is a biographical drama film about MySpace founder Tom Anderson.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "There is a city called Rome in every continent on Earth.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Big the Cat is a playable character in &quot;Sonic Generations&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In the &quot;Melancholy of Haruhi Suzumiya&quot; series, the narrator goes by the nickname Kyon.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                  "question": "The alternative rock band, They Might Be Giants, released their album &#039;Flood&#039; in 1990. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "easy",
                  "question": "Roger Federer is a famous soccer player.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "easy",
                  "question": "Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party in 1912.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}
]
